/**
 * Seed the Source Registry — the canonical declarative form of every source
 * we intend to track. ADR-0009 makes this file the single source of truth:
 * adding/modifying a source is a regular PR (no ADR); changes to schema,
 * enum values, or tier semantics need an ADR.
 *
 * Tier semantics (ADR-0009, locked):
 *   0 — pre-ADR-0009 baseline (the two starter rows)
 *   1 — Days 1–28: macro spine + first flagship inputs
 *   2 — Days 28–60: quarterly macro + first deep-dives
 *   3 — Days 60–120: vertical + utility deepening
 *   4 — Days 120–365: long tail of Year 1
 *   null — reference-only assets or Phase-2 deferred work
 *
 * Usage:
 *   pnpm exec tsx scripts/seed-source-registry.ts --dry-run
 *   pnpm exec tsx scripts/seed-source-registry.ts        # requires DATABASE_URL
 *
 * Idempotent: composes `upsertSource`, which keys on `source_id`. Re-running
 * updates mutable fields without rewriting `registered_at`.
 *
 * `db` and `upsertSource` are imported lazily so `--dry-run` works without
 * `DATABASE_URL` set — useful for CI smoke checks and local validation.
 */

import type { NewSourceRegistryRow } from '@/lib/db/schema/source-registry';

const ROWS: readonly NewSourceRegistryRow[] = [
  // ─── Tier 0 — pre-ADR-0009 baseline ────────────────────────────────
  {
    sourceId: 'nrb-cmefs-monthly',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Current Macroeconomic and Financial Situation',
    sourceUrl: 'https://www.nrb.org.np/category/current-macroeconomic-situation/',
    publicationFrequency: 'monthly',
    expectedReleaseWindow: '25th–30th of the month following the reporting period',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2073/74 onward (~2016)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-cmefs/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Provisional values revised in next release; historical values stable after 2 cycles',
    knownBreakageModes: ['url-changes-each-fy', 'pdf-format-shifts-at-fy-boundary'],
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 0,
    notes:
      'Starter source — existing PDFs already in repo at Stastical Information/CMEFs_Eng_Nine-Months_2082.83.pdf',
  },
  {
    sourceId: 'nrb-ncpi-table',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'NCPI Table 2(B)',
    sourceUrl: 'https://www.nrb.org.np/category/current-macroeconomic-situation/',
    publicationFrequency: 'monthly',
    expectedReleaseWindow: 'Bundled with CMEFs release',
    reportingPeriodType: 'nine_months_cumulative',
    fileFormat: 'csv',
    requiresTableExtraction: false,
    historicalCoverage: 'FY 2073/74 onward (table form available digitally; pre-2016 in PDF)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb_ncpi/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Aligned with CMEFs cycle',
    knownBreakageModes: ['header-row-position-shifts'],
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 0,
    notes: 'Existing CSV in repo at NRB Current/CMEFs_Table_Nine-Months_2082.83(2(B).csv',
  },

  // ─── Tier 1 — Days 1–28 (macro spine + first flagship inputs) ─────
  {
    sourceId: 'nrb-reserves-daily',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Daily foreign exchange reserve disclosure',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money In Pulse tile input. Audit-proposal cadence "daily" needs verification — disclosure may be weekly in practice.',
  },
  {
    sourceId: 'customs-monthly-trade',
    agency: 'Department of Customs',
    agencyShort: 'Customs',
    datasetName: 'Monthly trade statistics (imports + exports)',
    sourceUrl: 'https://www.customs.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money Out Pulse + flagship #2 (border arbitrage). Format: HTML landing + XLSX downloads.',
  },
  {
    sourceId: 'noc-petroleum-monthly',
    agency: 'Nepal Oil Corporation',
    agencyShort: 'NOC',
    datasetName: 'Petroleum imports + price-revision notices',
    sourceUrl: 'https://noc.org.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Money Out + flagship #4 (Public Enterprise X-Ray, NOC). Mix of PDF bulletins + HTML notices.',
  },
  {
    sourceId: 'fcgo-daily',
    agency: 'Financial Comptroller General Office',
    agencyShort: 'FCGO',
    datasetName: 'Daily revenue + expenditure (preliminary)',
    sourceUrl: 'https://fcgo.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money Wasted Pulse + Local Ledger. Preliminary values — confidence B by default. Audit-proposal flagged exact URL/format as TBD.',
  },
  {
    sourceId: 'nepse-eod',
    agency: 'Nepal Stock Exchange',
    agencyShort: 'NEPSE',
    datasetName: 'End-of-day quotes + market cap by stock',
    sourceUrl: 'https://www.nepalstock.com/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes: 'Money Captured Pulse + Private Capital. JSON-ish API; needs endpoint discovery.',
  },
  {
    sourceId: 'kalimati-daily-prices',
    agency: 'Kalimati Fruits & Vegetables Market Development Board',
    agencyShort: 'Kalimati',
    datasetName: 'Daily wholesale fruit & vegetable prices',
    sourceUrl: 'https://kalimatimarket.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Price Chain Nepal Pulse + flagship #2 ("Why Farmers Get Rs 25"). If Story #2 slips to month 3, may drop to Tier 2.',
  },

  // ─── Tier 2 — Days 28–60 (quarterly macro + first deep-dives) ─────
  {
    sourceId: 'pdmo-debt-bulletin',
    agency: 'Public Debt Management Office',
    agencyShort: 'PDMO',
    datasetName: 'Quarterly public debt bulletin',
    sourceUrl: 'https://pdmo.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Borrowed Time vertical. PDF tables; gated on Surya OCR readiness for Devanagari.',
  },
  {
    sourceId: 'nrb-banking-stats',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Banking and Financial Statistics (quarterly bulletin)',
    sourceUrl: 'https://www.nrb.org.np/category/banking-and-financial-statistics/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Money Captured + Collateral State. May be reconcilable with the monthly XLSX corpus (nrb-bfi-monthly-xlsx) — confirm before separate parser.',
  },
  {
    sourceId: 'nrb-loans-by-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Loans & advances by economic sector',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Collateral State vertical. Sometimes published inside CMEFs sub-tables, sometimes separately in Quarterly Economic Bulletin — verify before parser.',
  },
  {
    sourceId: 'dofe-labour-migration',
    agency: 'Department of Foreign Employment',
    agencyShort: 'DoFE',
    datasetName: 'Monthly labour permits + airport-records',
    sourceUrl: 'https://dofe.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Migration Industry vertical. District breakdown sometimes present.',
  },
  {
    sourceId: 'nrb-fdi-bulletin',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Status of FDI in Nepal (annual bulletin)',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Money In granular (by country/sector). Cadence and URL vary year-to-year.',
  },
  {
    sourceId: 'nso-gdp',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Quarterly GDP estimates',
    sourceUrl: 'https://nsonepal.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Where Money Becomes Wealth. Lagged 1–2 quarters by source.',
  },
  {
    sourceId: 'ntb-tourism-monthly',
    agency: 'Nepal Tourism Board',
    agencyShort: 'NTB',
    datasetName: 'Monthly arrivals + receipts',
    sourceUrl: 'https://ntb.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 2,
    notes: 'Tourism Value Chain. HTML page; per-tourist leakage derived from NRB BoP services.',
  },

  // ─── Tier 3 — Days 60–120 (verticals + utilities deepen) ──────────
  {
    sourceId: 'coops-regulatory-status',
    agency: 'Department of Cooperatives',
    agencyShort: 'DoC',
    datasetName: 'Cooperative regulatory status + Sahakari Bibhag directory',
    sourceUrl: 'https://www.deoc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Sahakari Tracker (signature-utility candidate).',
  },
  {
    sourceId: 'oag-audit-reports',
    agency: 'Office of the Auditor General',
    agencyShort: 'OAG',
    datasetName: 'Annual audit reports (federal + sectoral)',
    sourceUrl: 'https://oag.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Money Wasted. Heavy PDF prose; observations cite-only initially, structured later.',
  },
  {
    sourceId: 'dpm-public-enterprises-annual',
    agency: 'Office of the Prime Minister (DPM Office)',
    agencyShort: 'DPM',
    datasetName: 'Annual Performance Review of Public Enterprises (Yellow Book)',
    sourceUrl: 'https://opmcm.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Public Enterprise X-Ray. In-repo corpus at Financial Data/mof_documents/yellowbook/ (6 PDFs).',
  },
  {
    sourceId: 'moald-crop-production',
    agency: 'Ministry of Agriculture and Livestock Development',
    agencyShort: 'MoALD',
    datasetName: 'Seasonal crop production statistics',
    sourceUrl: 'https://moald.gov.np/',
    publicationFrequency: 'seasonal',
    reportingPeriodType: 'seasonal',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Soil Economy. PDF-heavy, variable format; needs Surya stack.',
  },
  {
    sourceId: 'mof-lmbis',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Line Ministry Budget Information System (federal budget execution)',
    sourceUrl: 'https://lmbis.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Budget Watch. Format and cadence flagged TBD in audit proposal.',
  },
  {
    sourceId: 'mof-sutra',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Sub-national Treasury Regulatory Application (SuTRA)',
    sourceUrl: 'https://sutra.fcgo.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Local Ledger (sub-national fiscal). Public reporting cadence variable.',
  },
  {
    sourceId: 'nnrfc-allocations',
    agency: 'National Natural Resources & Fiscal Commission',
    agencyShort: 'NNRFC',
    datasetName: 'Fiscal transfer allocations to provincial + local levels',
    sourceUrl: 'https://nnrfc.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Local Ledger (transfers).',
  },
  {
    sourceId: 'ird-revenue-monthly',
    agency: 'Inland Revenue Department',
    agencyShort: 'IRD',
    datasetName: 'Monthly revenue dashboard',
    sourceUrl: 'https://ird.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Tax State vertical.',
  },
  {
    sourceId: 'nea-generation-monthly',
    agency: 'Nepal Electricity Authority',
    agencyShort: 'NEA',
    datasetName: 'Monthly hydropower generation snapshots',
    sourceUrl: 'https://nea.org.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Hydropower Monitor. Audit proposal: NEA Annual Report + periodic snapshots — cadence "monthly" is best-case.',
  },
  {
    sourceId: 'doed-project-pipeline',
    agency: 'Department of Electricity Development',
    agencyShort: 'DoED',
    datasetName: 'Hydropower licence + project pipeline registry',
    sourceUrl: 'https://www.doed.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Hydropower Monitor (project pipeline).',
  },
  {
    sourceId: 'npc-project-bank',
    agency: 'National Planning Commission',
    agencyShort: 'NPC',
    datasetName: 'Project Bank + line-ministry monitoring',
    sourceUrl: 'https://npc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Money Wasted (project failure / execution tracking).',
  },
  {
    sourceId: 'nea-power-export',
    agency: 'Nepal Electricity Authority',
    agencyShort: 'NEA',
    datasetName: 'Power export revenue (to India)',
    sourceUrl: 'https://nea.org.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Money In (export receipts). Embedded in NEA Annual Report; sometimes monthly bulletins. Cadence "annual" is the safe assumption.',
  },

  // ─── Tier 4 — Days 120–365 (long tail of Year 1) ──────────────────
  {
    sourceId: 'census-2078-district',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Census 2078 district-level disaggregated data',
    sourceUrl: 'https://censusnepal.cbs.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'csv',
    requiresTableExtraction: false,
    historicalCoverage: 'Decennial (last 2078 BS / 2021 AD)',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'District MRI launch input. One-time ingest from in-repo Financial Data/Census/.',
  },
  {
    sourceId: 'moe-noc-student-outflow',
    agency: 'Ministry of Education',
    agencyShort: 'MoE',
    datasetName: 'No Objection Letter (NOC) data — student outflow',
    sourceUrl: 'https://moest.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Money Out + Migration. Reconcile with NRB BoP education line.',
  },
  {
    sourceId: 'ird-top-taxpayers',
    agency: 'Inland Revenue Department',
    agencyShort: 'IRD',
    datasetName: 'Top Taxpayers annual disclosure + LTO data',
    sourceUrl: 'https://ird.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Tax concentration.',
  },
  {
    sourceId: 'oag-lbl-local-audits',
    agency: 'Office of the Auditor General',
    agencyShort: 'OAG',
    datasetName: 'Local-body audit reports (OAG-LBL)',
    sourceUrl: 'https://oag.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Local Ledger audits. Published per FY across 753 local levels.',
  },
  {
    sourceId: 'dohs-hmis',
    agency: 'Department of Health Services',
    agencyShort: 'DoHS',
    datasetName: 'Health Management Information System (HMIS)',
    sourceUrl: 'https://dohs.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Where Money Becomes Wealth (health outcomes).',
  },
  {
    sourceId: 'cehrd-emis',
    agency: 'Centre for Education and Human Resource Development',
    agencyShort: 'CEHRD',
    datasetName: 'Education Management Information System (EMIS)',
    sourceUrl: 'https://cehrd.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Where Money Becomes Wealth (education outcomes).',
  },
  {
    sourceId: 'mof-budget-redbook',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Federal Budget Red Book + Mid-Term Review',
    sourceUrl: 'https://mof.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes:
      'Budget Watch. In-repo corpus at Financial Data/mof_documents/redbook/. Heavy OCR target (mostly Nepali).',
  },
  {
    sourceId: 'fepb-manpower-companies',
    agency: 'Foreign Employment Promotion Board',
    agencyShort: 'FEPB',
    datasetName: 'Recruitment-cost ceilings + manpower licenses',
    sourceUrl: 'https://fepb.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Migration Industry.',
  },
  {
    sourceId: 'dhm-hydro-met',
    agency: 'Department of Hydrology & Meteorology',
    agencyShort: 'DHM',
    datasetName: 'Flood / discharge / precipitation records',
    sourceUrl: 'https://dhm.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Climate Exposure (Hydropower + Climate vertical).',
  },
  {
    sourceId: 'ndrrma-damage-tally',
    agency: 'National Disaster Risk Reduction & Management Authority',
    agencyShort: 'NDRRMA',
    datasetName: 'Disaster damage tally',
    sourceUrl: 'https://bipadportal.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Climate Exposure.',
  },
  {
    sourceId: 'customs-exemptions',
    agency: 'Department of Customs',
    agencyShort: 'Customs',
    datasetName: 'Customs duty exemption list (budget annex)',
    sourceUrl: 'https://customs.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Tax State vertical (low priority).',
  },
  {
    sourceId: 'dolm-malpot-stats',
    agency: 'Department of Land Management & Archive',
    agencyShort: 'DoLM',
    datasetName: 'Malpot land-transaction statistics',
    sourceUrl: 'https://dolma.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Soil Economy (district-level land transactions).',
  },
  {
    sourceId: 'un-comtrade',
    agency: 'United Nations Statistics Division',
    agencyShort: 'UNSD',
    datasetName: 'UN Comtrade — trade partner perspective on Nepal',
    sourceUrl: 'https://comtradeplus.un.org/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Trade Partner perspective (light feed + reference).',
  },
  {
    sourceId: 'nrn-investment-tracker',
    agency: 'Non-Resident Nepali Association / MoF',
    agencyShort: 'NRN',
    datasetName: 'Diaspora / NRN investment + IBN disclosures',
    sourceUrl: 'https://nrna.org/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'C',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Diaspora Capital. Sources fragmented across NRN, MoF, IBN.',
  },
  {
    sourceId: 'mof-dfimis',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Aid Management Platform / DFIMIS — foreign aid disbursement',
    sourceUrl: 'https://amis.mof.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Aid management (Pillar 1 — foreign aid disbursement).',
  },

  // ─── Reference-only (registry IDs needed for citation) ────────────
  {
    sourceId: 'mof-economic-survey-annual',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Economic Survey (annual)',
    sourceUrl: 'https://mof.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes:
      'Macro narrative reference. Not parsed into approved_indicator_values; cited from stories.',
  },
  {
    sourceId: 'npc-16th-plan',
    agency: 'National Planning Commission',
    agencyShort: 'NPC',
    datasetName: '16th Five-Year Plan (FY 2081/82–2085/86)',
    sourceUrl: 'https://npc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Reference + project pipeline.',
  },
  {
    sourceId: 'nlss-survey',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Nepal Living Standards Survey (NLSS)',
    sourceUrl: 'https://nsonepal.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    historicalCoverage: 'Decadal; last 2010/11, next pending',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Household Ledger reference.',
  },
  {
    sourceId: 'ndhs-survey',
    agency: 'Ministry of Health and Population',
    agencyShort: 'MoHP',
    datasetName: 'Nepal Demographic & Health Survey (NDHS)',
    sourceUrl: 'https://mohp.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    historicalCoverage: 'Quinquennial',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Health reference.',
  },
  {
    sourceId: 'wb-wdi',
    agency: 'World Bank',
    agencyShort: 'WB',
    datasetName: 'World Development Indicators (WDI) — Nepal',
    sourceUrl: 'https://databank.worldbank.org/source/world-development-indicators',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark. Continuous availability via API.',
  },
  {
    sourceId: 'imf-article-iv',
    agency: 'International Monetary Fund',
    agencyShort: 'IMF',
    datasetName: 'Article IV consultation reports — Nepal',
    sourceUrl: 'https://www.imf.org/en/Countries/NPL',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'proprietary',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark.',
  },
  {
    sourceId: 'adb-ado-nepal',
    agency: 'Asian Development Bank',
    agencyShort: 'ADB',
    datasetName: 'Asian Development Outlook — Nepal section',
    sourceUrl: 'https://www.adb.org/countries/nepal/economy',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark.',
  },
];

export { ROWS };

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');

  if (dryRun) {
    console.log('[dry-run] would upsert the following source_registry rows:');
    console.log(JSON.stringify(ROWS, null, 2));
    console.log(`[dry-run] total: ${ROWS.length} rows`);
    process.exit(0);
  }

  // Lazy import: only require DATABASE_URL when we are actually hitting the DB.
  const { upsertSource } = await import('@/lib/db/repositories/source-registry');

  let failures = 0;
  for (const row of ROWS) {
    const result = await upsertSource(row);
    if (!result.ok) {
      failures += 1;
      console.error(`[seed] FAILED ${row.sourceId}:`, result.error);
      continue;
    }
    console.log(`[seed] upserted ${result.value.sourceId}`);
  }

  if (failures > 0) {
    console.error(`[seed] ${failures} of ${ROWS.length} rows failed`);
    process.exit(1);
  }

  console.log(`[seed] inserted/updated ${ROWS.length} source_registry rows`);
  process.exit(0);
}

// Only run main() when invoked directly, not when imported by check/gen
// scripts.
const isDirectInvocation = (() => {
  if (typeof process === 'undefined' || !process.argv[1]) return false;
  try {
    const invokedPath = process.argv[1].replace(/\\/g, '/');
    return invokedPath.endsWith('seed-source-registry.ts');
  } catch {
    return false;
  }
})();

if (isDirectInvocation) {
  main().catch((e: unknown) => {
    console.error('[seed] uncaught error:', e);
    process.exit(1);
  });
}
