/**
 * Seed the Source Registry — the canonical declarative form of every source
 * we intend to track. ADR-0009 makes this file the single source of truth:
 * adding/modifying a source is a regular PR (no ADR); changes to schema,
 * enum values, or tier semantics need an ADR.
 *
 * Tier semantics (ADR-0009, locked):
 *   0 — pre-ADR-0009 baseline (the two starter rows)
 *   1 — Days 1–28: macro spine + first flagship inputs
 *   2 — Days 28–60: quarterly macro + first deep-dives
 *   3 — Days 60–120: vertical + utility deepening
 *   4 — Days 120–365: long tail of Year 1
 *   null — reference-only assets or Phase-2 deferred work
 *
 * Usage:
 *   pnpm exec tsx scripts/seed-source-registry.ts --dry-run
 *   pnpm exec tsx scripts/seed-source-registry.ts        # requires DATABASE_URL
 *
 * Idempotent: composes `upsertSource`, which keys on `source_id`. Re-running
 * updates mutable fields without rewriting `registered_at`.
 *
 * `db` and `upsertSource` are imported lazily so `--dry-run` works without
 * `DATABASE_URL` set — useful for CI smoke checks and local validation.
 */

import type { NewSourceRegistryRow } from '@/lib/db/schema/source-registry';

const ROWS: readonly NewSourceRegistryRow[] = [
  // ─── Tier 0 — pre-ADR-0009 baseline ────────────────────────────────
  {
    sourceId: 'nrb-cmefs-monthly',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Current Macroeconomic and Financial Situation',
    sourceUrl: 'https://www.nrb.org.np/category/current-macroeconomic-situation/',
    publicationFrequency: 'monthly',
    expectedReleaseWindow: '25th–30th of the month following the reporting period',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2073/74 onward (~2016)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-cmefs/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Provisional values revised in next release; historical values stable after 2 cycles',
    knownBreakageModes: ['url-changes-each-fy', 'pdf-format-shifts-at-fy-boundary'],
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 0,
    notes:
      'Starter source — existing PDFs already in repo at Stastical Information/CMEFs_Eng_Nine-Months_2082.83.pdf',
  },
  {
    sourceId: 'nrb-ncpi-table',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'NCPI Table 2(B)',
    sourceUrl: 'https://www.nrb.org.np/category/current-macroeconomic-situation/',
    publicationFrequency: 'monthly',
    expectedReleaseWindow: 'Bundled with CMEFs release',
    reportingPeriodType: 'nine_months_cumulative',
    fileFormat: 'csv',
    requiresTableExtraction: false,
    historicalCoverage: 'FY 2073/74 onward (table form available digitally; pre-2016 in PDF)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb_ncpi/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Aligned with CMEFs cycle',
    knownBreakageModes: ['header-row-position-shifts'],
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 0,
    notes: 'Existing CSV in repo at NRB Current/CMEFs_Table_Nine-Months_2082.83(2(B).csv',
  },

  // ─── Tier 1 — Days 1–28 (macro spine + first flagship inputs) ─────
  {
    sourceId: 'nrb-reserves-daily',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Daily foreign exchange reserve disclosure',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money In Pulse tile input. Audit-proposal cadence "daily" needs verification — disclosure may be weekly in practice.',
  },
  {
    sourceId: 'customs-monthly-trade',
    agency: 'Department of Customs',
    agencyShort: 'Customs',
    datasetName: 'Monthly trade statistics (imports + exports)',
    sourceUrl: 'https://www.customs.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money Out Pulse + flagship #2 (border arbitrage). Format: HTML landing + XLSX downloads.',
  },
  {
    sourceId: 'noc-petroleum-monthly',
    agency: 'Nepal Oil Corporation',
    agencyShort: 'NOC',
    datasetName: 'Petroleum imports + price-revision notices',
    sourceUrl: 'https://noc.org.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Money Out + flagship #4 (Public Enterprise X-Ray, NOC). Mix of PDF bulletins + HTML notices.',
  },
  {
    sourceId: 'fcgo-daily',
    agency: 'Financial Comptroller General Office',
    agencyShort: 'FCGO',
    datasetName: 'Daily revenue + expenditure (preliminary)',
    sourceUrl: 'https://fcgo.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Money Wasted Pulse + Local Ledger. Preliminary values — confidence B by default. Audit-proposal flagged exact URL/format as TBD.',
  },
  {
    sourceId: 'nepse-eod',
    agency: 'Nepal Stock Exchange',
    agencyShort: 'NEPSE',
    datasetName: 'End-of-day quotes + market cap by stock',
    sourceUrl: 'https://www.nepalstock.com/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes: 'Money Captured Pulse + Private Capital. JSON-ish API; needs endpoint discovery.',
  },
  {
    sourceId: 'kalimati-daily-prices',
    agency: 'Kalimati Fruits & Vegetables Market Development Board',
    agencyShort: 'Kalimati',
    datasetName: 'Daily wholesale fruit & vegetable prices',
    sourceUrl: 'https://kalimatimarket.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 1,
    notes:
      'Price Chain Nepal Pulse + flagship #2 ("Why Farmers Get Rs 25"). If Story #2 slips to month 3, may drop to Tier 2.',
  },

  // ─── Tier 2 — Days 28–60 (quarterly macro + first deep-dives) ─────
  {
    sourceId: 'pdmo-debt-bulletin',
    agency: 'Public Debt Management Office',
    agencyShort: 'PDMO',
    datasetName: 'Quarterly public debt bulletin',
    sourceUrl: 'https://pdmo.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Borrowed Time vertical. PDF tables; gated on Surya OCR readiness for Devanagari.',
  },
  {
    sourceId: 'nrb-banking-stats',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Banking and Financial Statistics (quarterly bulletin)',
    sourceUrl: 'https://www.nrb.org.np/category/banking-and-financial-statistics/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Money Captured + Collateral State. May be reconcilable with the monthly XLSX corpus (nrb-bfi-monthly-xlsx) — confirm before separate parser.',
  },
  {
    sourceId: 'nrb-bfi-monthly-xlsx',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Banking & Financial Statistics — Monthly (BFI XLSX)',
    sourceUrl: 'https://www.nrb.org.np/category/monthly-statistics/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Monthly BFI snapshot XLSX (≈25 C-sheets/file), Aug 2021 → present. Parser scrapers/nrb_bfi; ingest:bfi-monthly → banking_sector_facts. Had a markdown profile but was missing from this seed (added 2026-06).',
  },
  {
    sourceId: 'nrb-loans-by-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Loans & advances by economic sector',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Collateral State vertical. Sometimes published inside CMEFs sub-tables, sometimes separately in Quarterly Economic Bulletin — verify before parser.',
  },
  {
    sourceId: 'dofe-labour-migration',
    agency: 'Department of Foreign Employment',
    agencyShort: 'DoFE',
    datasetName: 'Monthly labour permits + airport-records',
    sourceUrl: 'https://dofe.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Migration Industry vertical. District breakdown sometimes present.',
  },
  {
    sourceId: 'nrb-fdi-bulletin',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Status of FDI in Nepal (annual bulletin)',
    sourceUrl: 'https://www.nrb.org.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Money In granular (by country/sector). Cadence and URL vary year-to-year.',
  },
  {
    sourceId: 'nso-gdp',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Quarterly GDP estimates',
    sourceUrl: 'https://nsonepal.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes: 'Where Money Becomes Wealth. Lagged 1–2 quarters by source.',
  },
  {
    sourceId: 'ntb-tourism-monthly',
    agency: 'Nepal Tourism Board',
    agencyShort: 'NTB',
    datasetName: 'Monthly arrivals + receipts',
    sourceUrl: 'https://ntb.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 2,
    notes: 'Tourism Value Chain. HTML page; per-tourist leakage derived from NRB BoP services.',
  },

  // ─── Tier 3 — Days 60–120 (verticals + utilities deepen) ──────────
  {
    sourceId: 'coops-regulatory-status',
    agency: 'Department of Cooperatives',
    agencyShort: 'DoC',
    datasetName: 'Cooperative regulatory status + Sahakari Bibhag directory',
    sourceUrl: 'https://www.deoc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Sahakari Tracker (signature-utility candidate).',
  },
  {
    sourceId: 'oag-audit-reports',
    agency: 'Office of the Auditor General',
    agencyShort: 'OAG',
    datasetName: 'Annual audit reports (federal + sectoral)',
    sourceUrl: 'https://oag.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Money Wasted. Heavy PDF prose; observations cite-only initially, structured later.',
  },
  {
    sourceId: 'dpm-public-enterprises-annual',
    agency: 'Office of the Prime Minister (DPM Office)',
    agencyShort: 'DPM',
    datasetName: 'Annual Performance Review of Public Enterprises (Yellow Book)',
    sourceUrl: 'https://opmcm.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Public Enterprise X-Ray. In-repo corpus at Financial Data/mof_documents/yellowbook/ (6 PDFs). ' +
      'Active: Annex-1 (FY2080/81) → dne_facts via ingest:dne-yellowbook (ADR-0020); ' +
      'soe-government-share + soe-loan-principal, npr_thousand. Per-sector revenue/profit tables deferred.',
  },
  {
    sourceId: 'moald-crop-production',
    agency: 'Ministry of Agriculture and Livestock Development',
    agencyShort: 'MoALD',
    datasetName: 'Seasonal crop production statistics',
    sourceUrl: 'https://moald.gov.np/',
    publicationFrequency: 'seasonal',
    reportingPeriodType: 'seasonal',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Soil Economy. PDF-heavy, variable format; needs Surya stack.',
  },
  {
    sourceId: 'mof-lmbis',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Line Ministry Budget Information System (federal budget execution)',
    sourceUrl: 'https://lmbis.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Budget Watch. Format and cadence flagged TBD in audit proposal.',
  },
  {
    sourceId: 'mof-sutra',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Sub-national Treasury Regulatory Application (SuTRA)',
    sourceUrl: 'https://sutra.fcgo.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Local Ledger (sub-national fiscal). Public reporting cadence variable.',
  },
  {
    sourceId: 'nnrfc-allocations',
    agency: 'National Natural Resources & Fiscal Commission',
    agencyShort: 'NNRFC',
    datasetName: 'Fiscal transfer allocations to provincial + local levels',
    sourceUrl: 'https://nnrfc.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Local Ledger (transfers).',
  },
  {
    sourceId: 'local-fiscal-transfers-cleaned',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Federal fiscal transfers to 753 local levels, FY 2082/83 (pre-cleaned XLSX)',
    sourceUrl: 'https://mof.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Tier-1 first ingestable domain-fact corpus. Pre-cleaned by editorial team. Files in repo at Financial Data/mof_documents/Cleaned/. Consumer: scrapers/mof_fiscal_transfers/ (Worker P1, PR #37).',
  },
  {
    sourceId: 'ird-revenue-monthly',
    agency: 'Inland Revenue Department',
    agencyShort: 'IRD',
    datasetName: 'Monthly revenue dashboard',
    sourceUrl: 'https://ird.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 3,
    notes: 'Tax State vertical.',
  },
  {
    sourceId: 'nea-generation-monthly',
    agency: 'Nepal Electricity Authority',
    agencyShort: 'NEA',
    datasetName: 'Monthly hydropower generation snapshots',
    sourceUrl: 'https://nea.org.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Hydropower Monitor. Audit proposal: NEA Annual Report + periodic snapshots — cadence "monthly" is best-case.',
  },
  {
    sourceId: 'doed-project-pipeline',
    agency: 'Department of Electricity Development',
    agencyShort: 'DoED',
    datasetName: 'Hydropower licence + project pipeline registry',
    sourceUrl: 'https://www.doed.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Hydropower Monitor (project pipeline).',
  },
  {
    sourceId: 'npc-project-bank',
    agency: 'National Planning Commission',
    agencyShort: 'NPC',
    datasetName: 'Project Bank + line-ministry monitoring',
    sourceUrl: 'https://npc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes: 'Money Wasted (project failure / execution tracking).',
  },
  {
    sourceId: 'nea-power-export',
    agency: 'Nepal Electricity Authority',
    agencyShort: 'NEA',
    datasetName: 'Power export revenue (to India)',
    sourceUrl: 'https://nea.org.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Money In (export receipts). Embedded in NEA Annual Report; sometimes monthly bulletins. Cadence "annual" is the safe assumption.',
  },

  // ─── Tier 4 — Days 120–365 (long tail of Year 1) ──────────────────
  {
    sourceId: 'census-2078-district',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Census 2078 district-level disaggregated data',
    sourceUrl: 'https://censusnepal.cbs.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'csv',
    requiresTableExtraction: false,
    historicalCoverage: 'Decennial (last 2078 BS / 2021 AD)',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'District MRI launch input. One-time ingest from in-repo Financial Data/Census/.',
  },
  {
    sourceId: 'cbs-nphc-2021',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'National Population & Housing Census 2021 (2078 BS) — palika tables',
    sourceUrl: 'https://censusnepal.cbs.gov.np/results',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'csv',
    requiresTableExtraction: false,
    historicalCoverage: 'Decennial (2078 BS / 2021 AD)',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes:
      'Per-palika census tables (Hhld*/Indv*). Parser scrapers/cbs_nphc; ingest:census-2021 → census_facts. Had a markdown profile but was missing from this seed (added 2026-06). Parser currently supports a subset of demographic tables; financial-inclusion tables (bank accounts, loans, female asset ownership, absent population) need parser extension.',
  },
  {
    sourceId: 'moe-noc-student-outflow',
    agency: 'Ministry of Education',
    agencyShort: 'MoE',
    datasetName: 'No Objection Letter (NOC) data — student outflow',
    sourceUrl: 'https://moest.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Money Out + Migration. Reconcile with NRB BoP education line.',
  },
  {
    sourceId: 'ird-top-taxpayers',
    agency: 'Inland Revenue Department',
    agencyShort: 'IRD',
    datasetName: 'Top Taxpayers annual disclosure + LTO data',
    sourceUrl: 'https://ird.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Tax concentration.',
  },
  {
    sourceId: 'oag-lbl-local-audits',
    agency: 'Office of the Auditor General',
    agencyShort: 'OAG',
    datasetName: 'Local-body audit reports (OAG-LBL)',
    sourceUrl: 'https://oag.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Local Ledger audits. Published per FY across 753 local levels.',
  },
  {
    sourceId: 'dohs-hmis',
    agency: 'Department of Health Services',
    agencyShort: 'DoHS',
    datasetName: 'Health Management Information System (HMIS)',
    sourceUrl: 'https://dohs.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Where Money Becomes Wealth (health outcomes).',
  },
  {
    sourceId: 'cehrd-emis',
    agency: 'Centre for Education and Human Resource Development',
    agencyShort: 'CEHRD',
    datasetName: 'Education Management Information System (EMIS)',
    sourceUrl: 'https://cehrd.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Where Money Becomes Wealth (education outcomes).',
  },
  {
    sourceId: 'mof-budget-redbook',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Federal Budget Red Book + Mid-Term Review',
    sourceUrl: 'https://mof.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes:
      'Budget Watch. In-repo corpus at Financial Data/mof_documents/redbook/. Heavy OCR target (mostly Nepali).',
  },
  {
    sourceId: 'fepb-manpower-companies',
    agency: 'Foreign Employment Promotion Board',
    agencyShort: 'FEPB',
    datasetName: 'Recruitment-cost ceilings + manpower licenses',
    sourceUrl: 'https://fepb.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Migration Industry.',
  },
  {
    sourceId: 'dhm-hydro-met',
    agency: 'Department of Hydrology & Meteorology',
    agencyShort: 'DHM',
    datasetName: 'Flood / discharge / precipitation records',
    sourceUrl: 'https://dhm.gov.np/',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Climate Exposure (Hydropower + Climate vertical).',
  },
  {
    sourceId: 'ndrrma-damage-tally',
    agency: 'National Disaster Risk Reduction & Management Authority',
    agencyShort: 'NDRRMA',
    datasetName: 'Disaster damage tally',
    sourceUrl: 'https://bipadportal.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Climate Exposure.',
  },
  {
    sourceId: 'customs-exemptions',
    agency: 'Department of Customs',
    agencyShort: 'Customs',
    datasetName: 'Customs duty exemption list (budget annex)',
    sourceUrl: 'https://customs.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Tax State vertical (low priority).',
  },
  {
    sourceId: 'dolm-malpot-stats',
    agency: 'Department of Land Management & Archive',
    agencyShort: 'DoLM',
    datasetName: 'Malpot land-transaction statistics',
    sourceUrl: 'https://dolma.gov.np/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Soil Economy (district-level land transactions).',
  },
  {
    sourceId: 'un-comtrade',
    agency: 'United Nations Statistics Division',
    agencyShort: 'UNSD',
    datasetName: 'UN Comtrade — trade partner perspective on Nepal',
    sourceUrl: 'https://comtradeplus.un.org/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Trade Partner perspective (light feed + reference).',
  },
  {
    sourceId: 'nrn-investment-tracker',
    agency: 'Non-Resident Nepali Association / MoF',
    agencyShort: 'NRN',
    datasetName: 'Diaspora / NRN investment + IBN disclosures',
    sourceUrl: 'https://nrna.org/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    licenseStatus: 'gov_open',
    confidenceDefault: 'C',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 4,
    notes: 'Diaspora Capital. Sources fragmented across NRN, MoF, IBN.',
  },
  {
    sourceId: 'mof-dfimis',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Aid Management Platform / DFIMIS — foreign aid disbursement',
    sourceUrl: 'https://amis.mof.gov.np/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'html',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 4,
    notes: 'Aid management (Pillar 1 — foreign aid disbursement).',
  },

  // ─── Reference-only (registry IDs needed for citation) ────────────
  {
    sourceId: 'mof-economic-survey-annual',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Economic Survey (annual)',
    sourceUrl: 'https://mof.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes:
      'Macro narrative reference. Not parsed into approved_indicator_values; cited from stories.',
  },
  {
    sourceId: 'npc-16th-plan',
    agency: 'National Planning Commission',
    agencyShort: 'NPC',
    datasetName: '16th Five-Year Plan (FY 2081/82–2085/86)',
    sourceUrl: 'https://npc.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Reference + project pipeline.',
  },
  {
    sourceId: 'nlss-survey',
    agency: 'National Statistics Office',
    agencyShort: 'NSO',
    datasetName: 'Nepal Living Standards Survey (NLSS)',
    sourceUrl: 'https://nsonepal.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    historicalCoverage: 'Decadal; last 2010/11, next pending',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Household Ledger reference.',
  },
  {
    sourceId: 'ndhs-survey',
    agency: 'Ministry of Health and Population',
    agencyShort: 'MoHP',
    datasetName: 'Nepal Demographic & Health Survey (NDHS)',
    sourceUrl: 'https://mohp.gov.np/',
    publicationFrequency: 'ad_hoc',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    historicalCoverage: 'Quinquennial',
    licenseStatus: 'gov_open',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'Health reference.',
  },
  {
    sourceId: 'wb-wdi',
    agency: 'World Bank',
    agencyShort: 'WB',
    datasetName: 'World Development Indicators (WDI) — Nepal',
    sourceUrl: 'https://databank.worldbank.org/source/world-development-indicators',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'json',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark. Continuous availability via API.',
  },
  {
    sourceId: 'imf-article-iv',
    agency: 'International Monetary Fund',
    agencyShort: 'IMF',
    datasetName: 'Article IV consultation reports — Nepal',
    sourceUrl: 'https://www.imf.org/en/Countries/NPL',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'proprietary',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark.',
  },
  {
    sourceId: 'adb-ado-nepal',
    agency: 'Asian Development Bank',
    agencyShort: 'ADB',
    datasetName: 'Asian Development Outlook — Nepal section',
    sourceUrl: 'https://www.adb.org/countries/nepal/economy',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    licenseStatus: 'cc_by',
    confidenceDefault: 'A',
    status: 'active',
    ingestionMode: 'reference_only',
    tier: null,
    notes: 'International benchmark.',
  },

  // ─── Added from 2026-05 NRB/MoF catalog audits (Worker A + Worker B) ───

  // ─── NRB Database on Nepalese Economy (4 sector sources) ─────────────────

  {
    // Umbrella ingest source for the Database on Nepalese Economy XLSX corpus.
    // The scrapers/nrb_dne parser declares SOURCE_ID 'nrb-dne-xlsx'; this row is
    // its source_documents FK target (ADR-0010: a parser's SOURCE_ID must exist
    // in the seed). The per-sector nrb-db-* rows below are the finer-grained
    // catalog entries (one per sectoral page); a DNE ingest is tagged with this
    // umbrella id and the sector is captured in the indicator slug / parser_notes.
    sourceId: 'nrb-dne-xlsx',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Database on Nepalese Economy — structured time-series XLSX (all sectors)',
    sourceUrl: 'https://www.nrb.org.np/database-on-nepalese-economy/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage: 'Varies by series; Real/External/Fiscal/Monetary/Financial sectors',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb_dne/parser.py',
    parserVersion: '0.1.0',
    revisionPolicy:
      'Files updated in-place each cycle; download URL embeds upload date (scrape sector page for current link).',
    knownBreakageModes: ['upload-url-embeds-date-not-hardcodeable', 'sector-page-layout-shift'],
    confidenceDefault: 'B',
    status: 'active',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Ingest source for scrapers/nrb_dne (ingest:dne). Long-formats wide period-column XLSX into staging. No real files downloaded yet (2026-06). Subsumes nrb-db-external/fiscal/real/financial-sector catalog rows.',
  },
  {
    // NRB audit #1 — highest-priority NRB gap: BoP, forex, remittance, trade
    // all in structured XLSX — no PDF extraction needed. Feeds Pulse v1 directly.
    sourceId: 'nrb-db-external-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName:
      'Database on Nepalese Economy — External Sector (BoP, Forex, Trade, Remittance, Tourism)',
    sourceUrl: 'https://www.nrb.org.np/database-on-nepalese-economy/external-sector/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage: 'Estimated FY 2065/66 onward (~2008); individual series may vary',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-db-external-sector/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Files updated in-place at each release cycle; parser must fetch sector page to resolve current download URL',
    knownBreakageModes: [
      'upload-url-embeds-date-not-hardcodeable',
      'sector-page-must-be-scraped-for-current-link',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Money In + Money Out Pulse v1. Seven monthly XLSX series: BoP BPM5/BPM6, exchange rate, forex reserves, foreign trade, migrant workers/remittance, tourist arrivals. Most parse-friendly files in NRB catalog — no PDF extraction.',
  },
  {
    // NRB audit #2 — government revenue/expenditure (daily) + budgetary operation
    // (monthly) + outstanding debt (monthly). Feeds Money Out + Money Wasted pillars.
    sourceId: 'nrb-db-fiscal-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName:
      'Database on Nepalese Economy — Fiscal Sector (Government Revenue, Expenditure, Debt)',
    sourceUrl: 'https://www.nrb.org.np/database-on-nepalese-economy/fiscal-sector/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage: 'Estimated FY 2065/66 onward; coverage varies by dataset',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-db-fiscal-sector/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'NRB compiles from MoF; preliminary figures revised monthly',
    knownBreakageModes: [
      'upload-url-embeds-date-not-hardcodeable',
      'nrb-compiles-from-mof-preliminary-figures-revised',
    ],
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Money Out + Money Wasted pillars. Key datasets: Government Revenue and Expenditure (daily XLSX), Government Budgetary Operation (monthly), Outstanding Government Debt (monthly). Confidence B because NRB compiles from MoF; preliminary values revised.',
  },
  {
    // NRB audit #3 — BFI assets/deposits/loans, monetary survey, interest rates,
    // NEPSE. Feeds Money Captured pillar and validates nrb-bfi-monthly-xlsx.
    sourceId: 'nrb-db-financial-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName:
      'Database on Nepalese Economy — Financial Sector (BFI Assets, Deposits, Loans, Monetary Survey, Interest Rates, NEPSE)',
    sourceUrl: 'https://www.nrb.org.np/database-on-nepalese-economy/financial-sector/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage: 'Estimated FY 2065/66 onward; ~40 individual datasets',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-db-financial-sector/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Files updated in-place; parser must enumerate all datasets, not hardcode URLs',
    knownBreakageModes: [
      'upload-url-embeds-date-not-hardcodeable',
      'approx-40-datasets-parser-must-enumerate-all',
      'electronic-payment-transactions-structural-break-when-new-payment-rails-introduced',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Money Captured pillar. Sector-wise loan data here is a clean XLSX alternative to the complex multi-block BFI monthly XLSX. Reconcile with nrb-bfi-monthly-xlsx before separate parser.',
  },
  {
    // NRB audit #4 — GDP (quarterly old + new series), CPI monthly, agriculture,
    // industry, energy, provincial GDP. Foundational for "Where Money Becomes Wealth".
    sourceId: 'nrb-db-real-sector',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName:
      'Database on Nepalese Economy — Real Sector (GDP, CPI, Agriculture, Industry, Tourism, Energy)',
    sourceUrl: 'https://www.nrb.org.np/database-on-nepalese-economy/real-sector/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage:
      'National Accounts from ~FY 2060/61; quarterly GDP from ~2072; agriculture yearly',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-db-real-sector/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'NRB compiles from CBS/MoALD; preliminary; base-year revisions affect GDP series',
    knownBreakageModes: [
      'upload-url-embeds-date-not-hardcodeable',
      'quarterly-gdp-old-and-new-series-incompatible-base-year-revision',
      'provincial-gdp-separate-file',
    ],
    confidenceDefault: 'B',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Where Money Becomes Wealth pillar + Household Ledger Calculator per-capita baseline. NOTE: "Quarterly GDP (Old)" and "Quarterly GDP (New)" reflect a base-year revision — parsers must handle two incompatible series. Confidence B because NRB compiles from CBS/MoALD.',
  },

  // ─── NRB standalone publications ─────────────────────────────────────────

  {
    // NRB audit #5 — systemic risk, NPL ratios, capital adequacy. 16 issues,
    // FY 2012–FY 2023/24. Definitive Money Captured quality signal.
    sourceId: 'nrb-financial-stability-report',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Financial Stability Report',
    sourceUrl: 'https://www.nrb.org.np/category/financial-stability-report/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'Issue No. 1 (July 2012) → Issue No. 16 (FY 2023/24); 16 issues',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-financial-stability-report/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Annual; one issue per FY; no mid-year revisions',
    knownBreakageModes: [
      'url-slug-format-changed-older-issues-at-red-newer-at-bfr',
      'no-issue-yet-for-fy-2024-25',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Money Captured quality signal for Fact Ledger. High editorial value for Monthly Verdict (systemic risk, NPL, capital adequacy). URL slugs split across /red/ (older) and /bfr/ (newer issues).',
  },
  {
    // NRB audit #6 — directed credit subsidies mechanism: ~75 monthly XLSX releases
    // from Jeth 2078 → present. Essential for Money Captured + Borrowed Time.
    sourceId: 'nrb-concessional-loan',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Interest-Subsidized / Concessional Loan Monthly Statistics',
    sourceUrl: 'https://www.nrb.org.np/category/concessional-loan/',
    publicationFrequency: 'monthly',
    reportingPeriodType: 'monthly',
    fileFormat: 'xlsx',
    requiresTableExtraction: false,
    historicalCoverage: 'Jeth 2078 (May/June 2021) → present; ~75 months',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-concessional-loan/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Monthly; no revision cycle documented; treat each release as final for that month',
    knownBreakageModes: [
      'filename-uses-nepali-month-names-inconsistent-transliteration',
      'older-entries-pre-xlsx-transition-are-pdf-only',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Money Captured + Borrowed Time lens. Directed credit subsidies shape where private capital flows. XLSX from Jeth 2078; pre-XLSX entries are PDF-only. Filename transliteration varies (e.g., "Badau" vs "Bhadau").',
  },
  {
    // NRB audit #7 — quarterly Economic Bulletin, richest single-PDF compilation
    // ~200 time-series tables, deeper historical than CMEFs. ~35 issues back to 2003.
    sourceId: 'nrb-economic-bulletin',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Economic Bulletin & Indicators (Quarterly)',
    sourceUrl: 'https://www.nrb.org.np/category/quarterly-economic-bulletin/',
    publicationFrequency: 'quarterly',
    reportingPeriodType: 'quarterly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage:
      'Mid-April 2003 → Mid-January 2026; ~35 issues (quarterly: Jan/Apr/Jul/Oct)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-economic-bulletin/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Quarterly; each issue is a compilation snapshot; no revisions to prior issues',
    knownBreakageModes: [
      'pdf-size-approx-8mb-dense-tables',
      'url-slug-format-year-month-mid-month-name',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Richest single-PDF compilation of ~200 time-series tables across all economic sectors. Partially overlaps CMEFs but has deeper historical tables. No XLSX companion. Useful for gap-filling between CMEFs releases.',
  },
  {
    // NRB audit #8 — official audited macro tables by FY. 22 years back to 2003/04.
    // Required for back-filling Pulse indicators before monthly XLSX coverage (pre-2078).
    sourceId: 'nrb-annual-report',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'NRB Annual Report (English + Nepali)',
    sourceUrl: 'https://www.nrb.org.np/category/annual-reports',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2003/04 → FY 2024/25 (22 years)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-annual-report/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Annual; each report carries the final audited figures for that FY',
    knownBreakageModes: [
      'category-slug-annual-reports-plural-no-trailing-slash',
      'fiu-bsd-nbfisd-mlpsd-sub-reports-mixed-into-same-archive-category',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Gold standard for historical baseline: official audited macro-economic tables for each FY. Required for back-filling Pulse indicators before monthly XLSX coverage begins (pre-2078). Note: FIU, bank supervision, and non-bank FI supervision reports are mixed into the same archive category under different department slugs.',
  },
  {
    // NRB audit #10 — daily NRB balance sheet: monetary operations, OMO,
    // sterilization, reserve money. Replaces/extends vague nrb-reserves-daily stub.
    // Confirmed daily (not weekly as stub speculated).
    sourceId: 'nrb-central-bank-balance-sheet-daily',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'NRB Summarized Balance Sheet (Daily)',
    sourceUrl:
      'https://www.nrb.org.np/category/central-bank-survey-and-liquidity-position/?department=red',
    publicationFrequency: 'daily',
    reportingPeriodType: 'daily',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2080/81 onward confirmed; possibly earlier via month filter',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-central-bank-balance-sheet-daily/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Daily; preliminary; no revision cycle documented for individual day sheets',
    knownBreakageModes: [
      'page-uses-month-fy-filter-navigation-no-direct-archive-list',
      'url-pattern-consistent-red-yyyy-mm-dd-nrb-summarized-balance-sheet',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'automated_cron',
    tier: 2,
    notes:
      'Liquidity position / Pulse interbank-rate tile. Corrects and supersedes the vague nrb-reserves-daily stub (confirmed daily, not weekly). Small PDF ~38 KB, simple table. Validates Database on Nepalese Economy daily liquidity XLSX.',
  },
  {
    // NRB audit #11 — IMF MFSM-aligned view of Nepal financial system.
    // FY 2076/77–2079/80 confirmed. FY filter pages return "No posts" — must use
    // un-filtered category or direct slug.
    sourceId: 'nrb-financial-corporations-survey',
    agency: 'Nepal Rastra Bank',
    agencyShort: 'NRB',
    datasetName: 'Financial Corporations Survey (FCS)',
    sourceUrl: 'https://www.nrb.org.np/category/financial-corporations-survey/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2076/77–2079/80 confirmed; likely FY 2080/81+ when published',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/nrb-financial-corporations-survey/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Annual; groupings of multiple FYs in one release (e.g., "2076/77-2079/80")',
    knownBreakageModes: [
      'fy-filtered-category-pages-return-no-posts-use-unfiltered-category',
      'multi-fy-groupings-in-single-release',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'IMF MFSM-aligned standard-compliant view of Nepali financial system. Complements nrb-bfi-monthly-xlsx (NRB own format). Used in IMF Article IV reviews. FY filter pages return "No posts" even when data exists — use un-filtered category or search by post slug.',
  },

  // ─── MoF / FCGO / PDMO publications ──────────────────────────────────────

  {
    // MoF audit #2 — annual Finance Minister budget speech: headline revenue/
    // expenditure targets, policy priorities, sector allocations. Jestha 15 each year.
    sourceId: 'mof-budget-speech',
    agency: 'Ministry of Finance',
    agencyShort: 'MoF',
    datasetName: 'Budget Speech (बजेट वक्तव्य)',
    sourceUrl: 'https://mof.gov.np/en/publication/budget-speech-315',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage:
      'Estimated FY 2060 onward (~23+ editions); English translation ~1 week after Nepali release',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/mof-budget-speech/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Annual; no revision after presentation; supplementary appropriations are separate documents',
    knownBreakageModes: [
      'mof-gov-np-ssl-cert-chain-incomplete-add-mof-ca-to-trust-store',
      'url-structure-changes-each-fy',
      'english-translation-released-approx-1-week-after-nepali',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Budget Watch vertical + policy tagging. Annual headline fiscal targets: revenue, expenditure, capital, deficit. mof.gov.np SSL cert chain is incomplete — add the MoF CA certificate to the scraper trust store (do NOT disable TLS verification). PDF files are actually served from giwmscdnone.gov.np CDN (valid cert). Coverage estimate uncertain; verify on site once trust store is fixed.',
  },
  {
    // MoF audit #3 — FCGO audited all-of-government outturn data.
    // English CFS available FY 2018/19 onward; Nepali FY 2074/75 onward.
    // Highest-confidence fiscal outturn (audited).
    sourceId: 'fcgo-consolidated-financial-statements',
    agency: 'Financial Comptroller General Office',
    agencyShort: 'FCGO',
    datasetName: 'Consolidated Financial Statements (CFS) — Nepali + English',
    sourceUrl: 'https://fcgo.gov.np/category/consolidated-us',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'English: FY 2018/19 (2075/76) onward; Nepali: FY 2074/75 onward',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/fcgo-consolidated-financial-statements/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Annual; published Chaitra of following FY; audited outturn — no subsequent revision expected',
    knownBreakageModes: [
      'nepali-url-at-category-con-fin-statements-english-at-category-consolidated-us',
      'pdf-filenames-use-opaque-cdn-tokens-at-giwmscdnone-gov-np',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 1,
    notes:
      'Audited all-of-government outturn — highest-confidence fiscal data (A). Covers federal + 7 provinces + 753 local govts in consolidated form. English CFS available from FY 2018/19; Nepali from FY 2074/75. PDFs served from giwmscdnone.gov.np CDN.',
  },
  {
    // MoF audit #4 — PDMO monthly government debt stats.
    // Active monthly series (Chaitra 2082 = most recent). Separate from
    // quarterly pdmo-debt-bulletin.
    sourceId: 'pdmo-monthly-debt-statistics',
    agency: 'Public Debt Management Office',
    agencyShort: 'PDMO',
    datasetName: 'Monthly Government Debt Statistics (मासिक सरकारी ऋण तथ्याङ्क)',
    sourceUrl: 'https://pdmo.gov.np/pages/monthlyrepo',
    publicationFrequency: 'monthly',
    expectedReleaseWindow: 'Approximately 15th of the following month',
    reportingPeriodType: 'monthly',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'At least FY 2081/82 onward; likely earlier on site',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/pdmo-monthly-debt-statistics/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy:
      'Monthly; no revision cycle documented; treat each release as final for that month',
    knownBreakageModes: ['filename-pattern-varies-bs-month-name-nepali-or-english-inconsistent'],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 2,
    notes:
      'Borrowed Time vertical. Monthly debt stock: internal (T-bills + bonds + savings certs) + external. Active series — Chaitra 2082 (Apr 2026) is most recent. Distinct from the existing quarterly pdmo-debt-bulletin. Historical depth TBD; verify on site.',
  },
  {
    // MoF audit #5 — PDMO annual debt + share investment report.
    // Only FY 2080/81 and 2081/82 confirmed; historical depth uncertain.
    sourceId: 'pdmo-annual-debt-report',
    agency: 'Public Debt Management Office',
    agencyShort: 'PDMO',
    datasetName: 'Annual Report on Public Debt and Share Investment (वार्षिक प्रतिवेदन)',
    sourceUrl: 'https://pdmo.gov.np/',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: true,
    historicalCoverage: 'FY 2080/81 and FY 2081/82 confirmed; earlier editions TBD',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/pdmo-annual-debt-report/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Annual; no revision cycle documented',
    knownBreakageModes: [
      'content-pages-vary-by-year-no-stable-category-url',
      'pdf-filenames-use-nepali-unicode-in-cdn-path',
    ],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'manual_upload',
    tier: 3,
    notes:
      'Borrowed Time vertical. UNCERTAINTY: only 2 editions confirmed (FY 2080/81 + 2081/82); no stable category URL found. Historical depth and full URL pattern TBD. Flagged for Mother review before parser work.',
  },
  {
    // MoF audit #6 — PDMO medium-term debt strategy, 3-year forward window.
    // Reference/policy doc, not a time-series feed. 4 editions confirmed.
    sourceId: 'pdmo-mtds',
    agency: 'Public Debt Management Office',
    agencyShort: 'PDMO',
    datasetName: 'Medium-Term Debt Management Strategy (MTDS)',
    sourceUrl: 'https://pdmo.gov.np/pages/debtsteategy',
    publicationFrequency: 'annual',
    reportingPeriodType: 'annual',
    fileFormat: 'pdf',
    requiresTableExtraction: false,
    historicalCoverage: 'FY 2078/79–2080/81 through FY 2082/83–2084/85 (4 editions confirmed)',
    licenseStatus: 'gov_open',
    parserOwner: 'scrapers/pdmo-mtds/parser.py',
    parserVersion: '0.0.0',
    revisionPolicy: 'Annual; 3-year forward window; not a time-series feed',
    knownBreakageModes: ['url-typo-on-pdmo-site-debtsteategy-not-debtstrategy'],
    confidenceDefault: 'A',
    status: 'paused',
    ingestionMode: 'reference_only',
    tier: null,
    notes:
      'Borrowed Time + policy context. Strategy doc (not a statistical series). Reference-only — cite from stories, not ingested into approved_indicator_values. Note: PDMO site URL has a typo: "debtsteategy" (not "debtstrategy").',
  },
];

export { ROWS };

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');

  if (dryRun) {
    console.log('[dry-run] would upsert the following source_registry rows:');
    console.log(JSON.stringify(ROWS, null, 2));
    console.log(`[dry-run] total: ${ROWS.length} rows`);
    process.exit(0);
  }

  // Lazy import: only require DATABASE_URL when we are actually hitting the DB.
  const { upsertSource } = await import('@/lib/db/repositories/source-registry');

  let failures = 0;
  for (const row of ROWS) {
    const result = await upsertSource(row);
    if (!result.ok) {
      failures += 1;
      console.error(`[seed] FAILED ${row.sourceId}:`, result.error);
      continue;
    }
    console.log(`[seed] upserted ${result.value.sourceId}`);
  }

  if (failures > 0) {
    console.error(`[seed] ${failures} of ${ROWS.length} rows failed`);
    process.exit(1);
  }

  console.log(`[seed] inserted/updated ${ROWS.length} source_registry rows`);
  process.exit(0);
}

// Only run main() when invoked directly, not when imported by check/gen
// scripts.
const isDirectInvocation = (() => {
  if (typeof process === 'undefined' || !process.argv[1]) return false;
  try {
    const invokedPath = process.argv[1].replace(/\\/g, '/');
    return invokedPath.endsWith('seed-source-registry.ts');
  } catch {
    return false;
  }
})();

if (isDirectInvocation) {
  main().catch((e: unknown) => {
    console.error('[seed] uncaught error:', e);
    process.exit(1);
  });
}
