"""NRB BFI monthly XLSX schema-discovery probe.

Walks the BFI monthly XLSX corpus and catalogs, per file:
  * sheet names + count
  * for sheets that match the canonical C-series, header row contents
    (first 6 non-empty rows of cols 0..15) so drift in labels/period columns
    is visible
  * dimensions (max_row x max_col) for sheets C5/C6/C7 (the high-value sheets)

Writes a Markdown report at ``docs/research/nrb-bfi-schema-probe.md``.
Future parser briefs target groups based on this output.

Pure read-only; does not mutate the corpus. Re-runnable.

Usage:
    python -m scrapers.nrb_bfi.schema_probe
        [--input-dir <path>] [--output <md>]

Defaults:
    --input-dir = Financial Data/nrb_monthly_statistics/ (relative to repo
                   root inferred from this file's location).
    --output    = docs/research/nrb-bfi-schema-probe.md
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

import openpyxl

_KEY_SHEETS = ("C5", "C6", "C7")
_HEADER_ROW_SCAN = 6  # rows to dump from the top of each key sheet
_HEADER_COL_SCAN = 16  # cols of each header row to dump


@dataclass
class FileProbe:
    filename: str
    sheet_names: list[str]
    key_sheet_dims: dict[str, tuple[int, int]] = field(default_factory=dict)
    key_sheet_headers: dict[str, list[list[str]]] = field(default_factory=dict)
    error: str | None = None


def _norm_cell(c: object) -> str:
    if c is None:
        return ""
    s = str(c).strip()
    # Excel often stores trailing spaces from merged headers.
    return " ".join(s.split())


def _probe_file(path: Path) -> FileProbe:
    probe = FileProbe(filename=path.name, sheet_names=[])
    try:
        wb = openpyxl.load_workbook(filename=str(path), read_only=True, data_only=True)
    except (OSError, KeyError, ValueError) as exc:
        probe.error = f"open failed: {type(exc).__name__}: {exc}"
        return probe

    probe.sheet_names = list(wb.sheetnames)
    for sheet in _KEY_SHEETS:
        if sheet not in wb.sheetnames:
            continue
        ws = wb[sheet]
        max_row = ws.max_row or 0
        max_col = ws.max_column or 0
        probe.key_sheet_dims[sheet] = (max_row, max_col)
        headers: list[list[str]] = []
        for r_idx, row in enumerate(ws.iter_rows(values_only=True)):
            if r_idx >= _HEADER_ROW_SCAN:
                break
            cells = [_norm_cell(c) for c in row[:_HEADER_COL_SCAN]]
            # Trim trailing empties for readability.
            while cells and not cells[-1]:
                cells.pop()
            headers.append(cells)
        probe.key_sheet_headers[sheet] = headers
    wb.close()
    return probe


def _signature(probe: FileProbe) -> str:
    """Compact signature used to group files by structural similarity.

    Two files share a signature if they have the same sheet names AND
    the same (max_row, max_col) for each key sheet.
    """
    if probe.error:
        return f"ERROR:{probe.error[:60]}"
    sheets = ",".join(probe.sheet_names)
    dims = "|".join(
        f"{s}={probe.key_sheet_dims.get(s, '-')}" for s in _KEY_SHEETS
    )
    return f"sheets[{sheets}]|{dims}"


def _dim(p: FileProbe, sheet: str) -> str:
    return str(p.key_sheet_dims.get(sheet, "-"))


def _render_markdown(probes: list[FileProbe], input_dir: Path) -> str:
    groups: dict[str, list[FileProbe]] = {}
    for p in probes:
        groups.setdefault(_signature(p), []).append(p)
    sorted_groups = sorted(groups.items(), key=lambda kv: -len(kv[1]))

    lines: list[str] = [
        "# NRB BFI Monthly XLSX — Schema-Discovery Probe\n\n",
        "> Auto-generated by `scrapers/nrb_bfi/schema_probe.py`. Re-run "
        "`pnpm probe:nrb-bfi` to refresh.\n\n",
        f"**Corpus:** `{input_dir}`  \n**Files probed:** {len(probes)}  ",
        f"\n**Errors:** {sum(1 for p in probes if p.error)}\n\n",
        "## Schema groups\n\nFiles in the same group share sheet names + "
        "dimensions for C5/C6/C7. Parser briefs target groups, not files.\n\n",
        "| Group # | Files | Sheet count | C5 dims | C6 dims | C7 dims |\n",
        "|---|---|---|---|---|---|\n",
    ]
    for idx, (_sig, files) in enumerate(sorted_groups, start=1):
        s = files[0]
        if s.error:
            lines.append(f"| G{idx} | {len(files)} | ERROR | {s.error[:40]} | — | — |\n")
        else:
            lines.append(
                f"| G{idx} | {len(files)} | {len(s.sheet_names)} | "
                f"{_dim(s, 'C5')} | {_dim(s, 'C6')} | {_dim(s, 'C7')} |\n"
            )

    lines.append("\n## Per-file inventory\n\n")
    lines.append("| File | Sheets | C5 (r×c) | C6 (r×c) | C7 (r×c) | Status |\n")
    lines.append("|---|---:|---|---|---|---|\n")
    for p in sorted(probes, key=lambda x: x.filename):
        if p.error:
            lines.append(f"| `{p.filename}` | — | — | — | — | error: {p.error[:40]} |\n")
        else:
            lines.append(
                f"| `{p.filename}` | {len(p.sheet_names)} | "
                f"{_dim(p, 'C5')} | {_dim(p, 'C6')} | {_dim(p, 'C7')} | ok |\n"
            )

    lines.append(
        "\n## Notes\n\n"
        "- Canonical month (Bhadau 2082) carries 25 sheets (C1..C25).\n"
        "- Largest group is the parser-extension starting point; smaller "
        "groups need per-group dispatch.\n"
        "- Header excerpts below make label/period drift visible without "
        "opening Excel.\n\n"
        "## Header excerpts (one sample per group)\n"
    )
    for idx, (_sig, files) in enumerate(sorted_groups, start=1):
        s = files[0]
        if s.error:
            continue
        lines.append(f"\n### G{idx} — `{s.filename}` ({len(files)} file(s))\n")
        for sheet in _KEY_SHEETS:
            headers = s.key_sheet_headers.get(sheet, [])
            if not headers:
                continue
            lines.append(f"\n**{sheet}** (first {_HEADER_ROW_SCAN}r × {_HEADER_COL_SCAN}c):\n\n```\n")
            for r in headers:
                lines.append(" | ".join(r) + "\n")
            lines.append("```\n")
    return "".join(lines)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = _repo_root()
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=root / "Financial Data" / "nrb_monthly_statistics",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "docs" / "research" / "nrb-bfi-schema-probe.md",
    )
    args = parser.parse_args(argv)

    input_dir: Path = args.input_dir
    if not input_dir.exists():
        sys.stderr.write(f"input dir does not exist: {input_dir}\n")
        return 2

    xlsx_files = sorted(input_dir.glob("*.xlsx"))
    if not xlsx_files:
        sys.stderr.write(f"no XLSX files found under {input_dir}\n")
        return 2

    probes = [_probe_file(p) for p in xlsx_files]

    output: Path = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_render_markdown(probes, input_dir), encoding="utf-8")

    sys.stdout.write(
        f"probed {len(probes)} files, "
        f"{sum(1 for p in probes if p.error)} errors -> {output}\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
