"""Acceptance tests for the NRB BFI XLSX parser v0.1.0.

These exercise the public surface (``parse``) plus the slug / period /
normalisation helpers. The fixture XLSX lives at
``scrapers/nrb_bfi/fixtures/Saun-2082-fixture.xlsx`` and is regenerated by
``fixtures/_build_fixture.py`` — it is the deterministic miniature of a
real Saun-2082 snapshot.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pytest

from _common.types import StagingBfiRowDraft
from nrb_bfi._filename import FilenameUnparseableError, parse_snapshot_filename
from nrb_bfi._normalize import coerce_float, has_devanagari_digit, normalise_digits, slugify
from nrb_bfi._periods import label_to_period, parse_mid_month_label, snapshot_period_ad
from nrb_bfi.parser import PARSER_VERSION, parse

_FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "Saun-2082-fixture.xlsx"


# ─── Filename parsing ──────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("stem", "expected"),
    [
        ("Shrawan-2078-2.xlsx", ("Shrawan", 2078)),
        ("Saun-2082-Publish.xlsx", ("Shrawan", 2082)),
        ("Bhadau_2082_Publish.xlsx", ("Bhadra", 2082)),
        ("Ashar2079_Publish.xlsx", ("Ashadh", 2079)),
        ("Asoj_2079_PublishV1.xlsx", ("Ashwin", 2079)),
        ("Magh2078_NFRS_Publish-1.xlsx", ("Magh", 2078)),
        ("Manghir-2078.xlsx", ("Mangsir", 2078)),
        ("Chaitra-2078.xlsx", ("Chait", 2078)),
        ("Baishakh-2079.xlsx", ("Baisakh", 2079)),
        ("Jestha2079_PublishV1.xlsx", ("Jestha", 2079)),
    ],
)
def test_parse_snapshot_filename_known_corpus(stem: str, expected: tuple[str, int]) -> None:
    assert parse_snapshot_filename(stem) == expected


def test_parse_snapshot_filename_unknown_raises() -> None:
    with pytest.raises(FilenameUnparseableError):
        parse_snapshot_filename("PoushDataset_2082.xlsx" + "_xxxx-nonsense")  # noqa: PLW2901
    with pytest.raises(FilenameUnparseableError):
        parse_snapshot_filename("Unknown-XYZ-0000.xlsx")


# ─── Normalisation ─────────────────────────────────────────────────────


def test_slugify_strips_outline_numbers() -> None:
    assert slugify(" 1.1.2.3  Upto 3 Months ") == "upto-3-months"
    assert slugify("a. Paid-up Capital") == "paid-up-capital"
    assert slugify("CAPITAL FUND") == "capital-fund"
    assert slugify("Agricultural and Forest Related") == "agricultural-and-forest-related"


def test_coerce_float_handles_strings_and_commas() -> None:
    assert coerce_float("1,234.56") == 1234.56
    assert coerce_float(None) is None
    assert coerce_float("") is None
    assert coerce_float("-") is None
    assert coerce_float("N/A") is None
    assert coerce_float(42) == 42.0


def test_devanagari_digit_normalisation() -> None:
    assert has_devanagari_digit("१२३")
    assert not has_devanagari_digit("123")
    assert normalise_digits("१२३.४५") == "123.45"
    assert coerce_float("१२३.४५") == 123.45


# ─── Period resolution ─────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("label", "expected"),
    [
        ("Mid-July", 7),
        ("Mid-Aug", 8),
        ("Mid-Sept", 9),
        ("Mid-Sep", 9),
        ("Mid-June", 6),
        ("Mid-Jan", 1),
    ],
)
def test_parse_mid_month_label(label: str, expected: int) -> None:
    assert parse_mid_month_label(label) == expected


def test_label_to_period_mid_aug_2025() -> None:
    resolved = label_to_period("Mid-Aug", 2025)
    assert resolved is not None
    ad_start, ad_end, period_bs, fy_bs, bs_m, bs_y = resolved
    assert ad_end == datetime(2025, 8, 15, tzinfo=ad_end.tzinfo)
    assert ad_start == datetime(2025, 7, 15, tzinfo=ad_start.tzinfo)
    assert bs_m == "Shrawan"
    assert bs_y == 2082
    assert "Shrawan" in period_bs
    assert fy_bs == "2082/83"


def test_snapshot_period_ad_for_saun() -> None:
    start, end = snapshot_period_ad("Shrawan", 2082)
    # Shrawan 2082 ~= mid-July 2025 -> mid-Aug 2025
    assert start.year == 2025
    assert start.month == 7
    assert end.month == 8


# ─── End-to-end parse on fixture ───────────────────────────────────────


@pytest.fixture(scope="module")
def fixture_result() -> object:
    return parse(str(_FIXTURE), "fixture-id")


def test_fixture_parses_successfully(fixture_result: object) -> None:
    assert fixture_result.status == "success"  # type: ignore[attr-defined]
    assert fixture_result.parser_version == PARSER_VERSION  # type: ignore[attr-defined]
    assert len(fixture_result.errors) == 0  # type: ignore[attr-defined]


def test_fixture_emits_rows_from_all_target_sheets(fixture_result: object) -> None:
    sheets = {r.source_sheet for r in fixture_result.staging_rows}  # type: ignore[attr-defined]
    assert sheets == {"C4", "C5", "C6", "C7"}


def test_fixture_c4_section_prefix_applied(fixture_result: object) -> None:
    slugs = {
        r.indicator_slug
        for r in fixture_result.staging_rows  # type: ignore[attr-defined]
        if r.source_sheet == "C4"
    }
    assert "credit-deposit-ratios--total-deposit-gdp" in slugs
    assert "liquidity-ratios--total-liquid-assets-total-deposit" in slugs


def test_fixture_c5_section_prefix_applied(fixture_result: object) -> None:
    slugs = {
        r.indicator_slug
        for r in fixture_result.staging_rows  # type: ignore[attr-defined]
        if r.source_sheet == "C5"
    }
    # Subitems get prefixed by the CAPITAL FUND section.
    assert "capital-fund--paid-up-capital" in slugs
    assert "capital-fund--statutory-reserves" in slugs
    # Section row itself emits a total.
    assert "capital-fund" in slugs


def test_fixture_c5_bank_class_dimension_complete(fixture_result: object) -> None:
    rows = [
        r
        for r in fixture_result.staging_rows  # type: ignore[attr-defined]
        if r.source_sheet == "C5" and r.indicator_slug == "capital-fund--paid-up-capital"
    ]
    classes = {r.bank_class for r in rows}
    # All four bank classes from a C5 sheet appear.
    assert classes == {"commercial", "development", "finance", "system_total"}


def test_fixture_c7_sector_slugs(fixture_result: object) -> None:
    slugs = {
        r.indicator_slug
        for r in fixture_result.staging_rows  # type: ignore[attr-defined]
        if r.source_sheet == "C7"
    }
    assert "agricultural-and-forest-related" in slugs
    assert "construction" in slugs


def test_fixture_units_are_canonical(fixture_result: object) -> None:
    units = {r.unit for r in fixture_result.staging_rows}  # type: ignore[attr-defined]
    # C4 -> percent; C5/C6/C7 -> NPR_million.
    assert units <= {"percent", "NPR_million"}


def test_fixture_reporting_periods_are_monthly(fixture_result: object) -> None:
    types = {r.reporting_period_type for r in fixture_result.staging_rows}  # type: ignore[attr-defined]
    assert types == {"monthly"}


def test_fixture_value_for_paid_up_capital_matches(fixture_result: object) -> None:
    # system_total Mid-Aug 2025 paid-up capital from the fixture.
    target = [
        r
        for r in fixture_result.staging_rows  # type: ignore[attr-defined]
        if r.source_sheet == "C5"
        and r.indicator_slug == "capital-fund--paid-up-capital"
        and r.bank_class == "system_total"
        and r.reporting_period_ad_end.month == 8
        and r.reporting_period_ad_end.year == 2025
    ]
    assert len(target) == 1
    assert target[0].value == pytest.approx(444576.20)


# ─── Failure modes ─────────────────────────────────────────────────────


def test_missing_file_returns_failure() -> None:
    result = parse("does/not/exist.xlsx", "id")
    assert result.status == "failure"
    assert any(e.error_class == "Other" for e in result.errors)


def test_row_is_correct_dataclass(fixture_result: object) -> None:
    rows = fixture_result.staging_rows  # type: ignore[attr-defined]
    assert all(isinstance(r, StagingBfiRowDraft) for r in rows)
