"""Tests for wb_knomad_bilateral.parser.

Tests are split into:
  1. Metadata / constants — no file I/O
  2. Failure paths — missing file, wrong extension, no Nepal column
  3. Happy path — synthetic XLSX fixture (generated by conftest.py)
  4. Year inference — filename vs. sheet content
"""

from __future__ import annotations

import io
import pathlib

import openpyxl
import pytest

from wb_knomad_bilateral.parser import PARSER_VERSION, SOURCE_ID, parse
from wb_knomad_bilateral.tests.conftest import (
    EXPECTED_INDIA,
    EXPECTED_MALAYSIA,
    EXPECTED_QATAR,
    EXPECTED_TOTAL,
    EXPECTED_UAE,
    EXPECTED_USA,
    SYNTHETIC_YEAR,
)


# ── 1. Metadata ────────────────────────────────────────────────────────────────


def test_parser_version() -> None:
    assert PARSER_VERSION == "0.2.0"


def test_source_id() -> None:
    assert SOURCE_ID == "wb-knomad-bilateral-remittance"


# ── 2. Failure paths ───────────────────────────────────────────────────────────


def test_missing_file_returns_failure(tmp_path: pathlib.Path) -> None:
    """parse() on a non-existent file must return status='failure'."""
    result = parse(str(tmp_path / "no-such-file.xlsx"), "doc-001")
    assert result.status == "failure"
    assert result.parser_version == PARSER_VERSION
    assert result.staging_rows == []
    assert len(result.errors) == 1
    assert result.errors[0].error_class == "Other"
    assert "not found" in result.errors[0].error_detail


def test_invalid_file_returns_failure(tmp_path: pathlib.Path) -> None:
    """parse() on a non-XLSX (e.g. HTML) file must return status='failure'."""
    bad_file = tmp_path / "knomad-bilateral-2024.xlsx"
    bad_file.write_bytes(b"<html>not an xlsx</html>")
    result = parse(str(bad_file), "doc-002")
    assert result.status == "failure"
    assert result.errors[0].error_class == "EncodingError"


def _make_xlsx_no_nepal(tmp_path: pathlib.Path) -> pathlib.Path:
    """Create a workbook with a 'Bilateral_Remittance' sheet that has no Nepal column."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Bilateral_Remittance"  # type: ignore[union-attr]
    ws.append([None, "China", "India", "USA"])  # type: ignore[union-attr]
    ws.append(["India", 100.0, None, 50.0])  # type: ignore[union-attr]
    path = tmp_path / "knomad-bilateral-2024.xlsx"
    buf = io.BytesIO()
    wb.save(buf)
    path.write_bytes(buf.getvalue())
    return path


def test_no_nepal_column_returns_failure(tmp_path: pathlib.Path) -> None:
    """parse() must return status='failure' with ColumnMissing when Nepal column absent."""
    path = _make_xlsx_no_nepal(tmp_path)
    result = parse(str(path), "doc-003")
    assert result.status == "failure"
    assert result.errors[0].error_class == "ColumnMissing"
    assert "Nepal" in result.errors[0].error_detail


def _make_xlsx_no_bilateral_sheet(tmp_path: pathlib.Path) -> pathlib.Path:
    """Workbook with two sheets, neither named 'bilateral*'."""
    wb = openpyxl.Workbook()
    ws1 = wb.active
    ws1.title = "Cover"  # type: ignore[union-attr]
    ws2 = wb.create_sheet("Notes")
    ws2.append(["nothing here"])  # type: ignore[union-attr]
    path = tmp_path / "knomad-bilateral-2024.xlsx"
    buf = io.BytesIO()
    wb.save(buf)
    path.write_bytes(buf.getvalue())
    return path


def test_no_bilateral_sheet_returns_failure(tmp_path: pathlib.Path) -> None:
    """parse() must return status='failure' with ColumnMissing when no bilateral sheet."""
    path = _make_xlsx_no_bilateral_sheet(tmp_path)
    result = parse(str(path), "doc-004")
    assert result.status == "failure"
    assert result.errors[0].error_class == "ColumnMissing"
    assert "bilateral" in result.errors[0].error_detail.lower()


# ── 3. Happy path — synthetic XLSX ────────────────────────────────────────────


def test_parse_returns_success(synthetic_xlsx_path: pathlib.Path) -> None:
    """parse() on synthetic fixture must return status='success'."""
    result = parse(str(synthetic_xlsx_path), "doc-syn-001")
    assert result.status == "success"
    assert result.parser_version == PARSER_VERSION
    assert result.errors == []
    assert len(result.staging_rows) > 0


def test_all_staging_rows_have_correct_unit(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-002")
    for row in result.staging_rows:
        assert row.unit == "usd_million", f"unexpected unit on {row.indicator_slug_raw}"


def test_all_staging_rows_annual_period(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-003")
    for row in result.staging_rows:
        assert row.reporting_period_type == "annual"


def test_all_staging_rows_confidence_A(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-004")
    for row in result.staging_rows:
        assert row.confidence_grade_proposed == "A"


def _get_row(result_rows: list, slug: str):  # type: ignore[type-arg]
    matches = [r for r in result_rows if r.indicator_slug_raw == slug]
    assert len(matches) == 1, f"expected exactly 1 row for {slug!r}; got {len(matches)}"
    return matches[0]


def test_india_corridor_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-005")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-from-india-annual")
    assert row.value == pytest.approx(EXPECTED_INDIA)


def test_qatar_corridor_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-006")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-from-qatar-annual")
    assert row.value == pytest.approx(EXPECTED_QATAR)


def test_uae_corridor_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-007")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-from-uae-annual")
    assert row.value == pytest.approx(EXPECTED_UAE)


def test_malaysia_corridor_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-008")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-from-malaysia-annual")
    assert row.value == pytest.approx(EXPECTED_MALAYSIA)


def test_usa_corridor_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-009")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-from-usa-annual")
    assert row.value == pytest.approx(EXPECTED_USA)


def test_total_extracted(synthetic_xlsx_path: pathlib.Path) -> None:
    result = parse(str(synthetic_xlsx_path), "doc-syn-010")
    row = _get_row(result.staging_rows, "knomad-remittance-to-nepal-total-annual")
    assert row.value == pytest.approx(EXPECTED_TOTAL)


def test_fiscal_year_bs_label(synthetic_xlsx_path: pathlib.Path) -> None:
    """BS fiscal year label for AD 2024 must be '2081/82'."""
    result = parse(str(synthetic_xlsx_path), "doc-syn-011")
    assert result.staging_rows[0].fiscal_year_bs == "2081/82"


def test_fiscal_year_ad_label(synthetic_xlsx_path: pathlib.Path) -> None:
    """AD fiscal year label for SYNTHETIC_YEAR=2024 must be '2024/25'."""
    result = parse(str(synthetic_xlsx_path), "doc-syn-012")
    assert result.staging_rows[0].fiscal_year_ad_label == "2024/25"


def test_publication_date_year(synthetic_xlsx_path: pathlib.Path) -> None:
    """Publication date must be in AD year+1 (KNOMAD releases ~June of following year)."""
    result = parse(str(synthetic_xlsx_path), "doc-syn-013")
    pub = result.staging_rows[0].publication_date_ad
    assert pub.year == SYNTHETIC_YEAR + 1
    assert pub.month == 6


def test_parser_notes_mention_year(synthetic_xlsx_path: pathlib.Path) -> None:
    """parser_notes must reference the calendar year for audit traceability."""
    result = parse(str(synthetic_xlsx_path), "doc-syn-014")
    for row in result.staging_rows:
        assert str(SYNTHETIC_YEAR) in (row.parser_notes or "")


# ── 4. Year inference fallback ────────────────────────────────────────────────


def _make_xlsx_no_year_in_name(tmp_path: pathlib.Path) -> pathlib.Path:
    """Workbook with a bilateral sheet but no year in filename — should fail period inference."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Bilateral_Remittance"  # type: ignore[union-attr]
    ws.append([None, "Nepal"])  # type: ignore[union-attr]
    ws.append(["India", 1000.0])  # type: ignore[union-attr]
    path = tmp_path / "knomad-bilateral-data.xlsx"  # no year
    buf = io.BytesIO()
    wb.save(buf)
    path.write_bytes(buf.getvalue())
    return path


def test_no_year_in_filename_returns_failure(tmp_path: pathlib.Path) -> None:
    """parse() must fail with PeriodAmbiguous when year cannot be inferred."""
    path = _make_xlsx_no_year_in_name(tmp_path)
    result = parse(str(path), "doc-year-001")
    assert result.status == "failure"
    assert result.errors[0].error_class == "PeriodAmbiguous"


def _make_xlsx_year_in_sheet(tmp_path: pathlib.Path, year: int = 2023) -> pathlib.Path:
    """Workbook where year appears in cell A1, not the filename."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Bilateral_Remittance"  # type: ignore[union-attr]
    # Row 0: year mention in first cell, then Nepal header
    ws.append([f"Bilateral Remittance Matrix {year}", "Nepal"])  # type: ignore[union-attr]
    ws.append(["India", 900.0])  # type: ignore[union-attr]
    path = tmp_path / "knomad-bilateral-data.xlsx"  # no year in filename
    buf = io.BytesIO()
    wb.save(buf)
    path.write_bytes(buf.getvalue())
    return path


def test_year_inferred_from_sheet_content(tmp_path: pathlib.Path) -> None:
    """parse() should infer year from sheet header cell when filename has no year."""
    path = _make_xlsx_year_in_sheet(tmp_path, year=2023)
    result = parse(str(path), "doc-year-002")
    # Year found in sheet → no PeriodAmbiguous; should succeed or partial
    assert result.status in ("success", "partial")
    assert result.staging_rows[0].fiscal_year_bs == "2080/81"


# ── 5. Real fixture tests (skipped if file not present) ───────────────────

REAL_FIXTURE_2021 = (
    pathlib.Path(__file__).resolve().parent
    / "fixtures"
    / "bilateral_remittance_matrix_2021.xlsx"
)


@pytest.mark.skipif(
    not REAL_FIXTURE_2021.exists(),
    reason="real KNOMAD 2021 fixture not downloaded (run archive.org recovery)",
)
def test_real_fixture_2021_success() -> None:
    """Parser must return success against the real 2021 KNOMAD matrix."""
    res = parse(str(REAL_FIXTURE_2021), "real-2021")
    assert res.status == "success", f"Expected success, got {res.status}: {res.errors}"
    assert res.parser_version == PARSER_VERSION
    assert len(res.errors) == 0


@pytest.mark.skipif(
    not REAL_FIXTURE_2021.exists(),
    reason="real KNOMAD 2021 fixture not downloaded",
)
def test_real_fixture_2021_nepal_india_value() -> None:
    """India corridor value from real 2021 matrix must be > 1000 USD million.

    Verified against raw cell value in the KNOMAD Dec-2022 release:
    India -> Nepal = 1583.40 USD million (CY2021).
    """
    res = parse(str(REAL_FIXTURE_2021), "real-2021")
    india = next(
        (r for r in res.staging_rows if r.indicator_slug_raw == "knomad-remittance-to-nepal-from-india-annual"),
        None,
    )
    assert india is not None, "India corridor not found in real 2021 fixture"
    assert india.value == pytest.approx(1583.40, rel=0.01), (
        f"India->Nepal 2021 value {india.value} outside expected range"
    )
    assert india.unit == "usd_million"


@pytest.mark.skipif(
    not REAL_FIXTURE_2021.exists(),
    reason="real KNOMAD 2021 fixture not downloaded",
)
def test_real_fixture_2021_total_plausible() -> None:
    """World-row total (Nepal inflows) from CY2021 must be in [5000, 12000] USD million."""
    res = parse(str(REAL_FIXTURE_2021), "real-2021")
    total = next(
        (r for r in res.staging_rows if r.indicator_slug_raw == "knomad-remittance-to-nepal-total-annual"),
        None,
    )
    assert total is not None, "Total row not found in real 2021 fixture"
    assert 5000 < total.value < 12000, f"Total {total.value} outside plausible range [5000, 12000]"


@pytest.mark.skipif(
    not REAL_FIXTURE_2021.exists(),
    reason="real KNOMAD 2021 fixture not downloaded",
)
def test_real_fixture_2021_fiscal_year_bs() -> None:
    """CY2021 must map to BS FY 2078/79."""
    res = parse(str(REAL_FIXTURE_2021), "real-2021")
    assert res.staging_rows[0].fiscal_year_bs == "2078/79"


@pytest.mark.skipif(
    not REAL_FIXTURE_2021.exists(),
    reason="real KNOMAD 2021 fixture not downloaded",
)
def test_real_fixture_2021_no_romania_false_positive() -> None:
    """Romania must NOT appear as an 'oman' corridor row (substring guard)."""
    res = parse(str(REAL_FIXTURE_2021), "real-2021")
    slugs = [r.indicator_slug_raw for r in res.staging_rows]
    # Oman row in real 2021 data is None, so it should be absent
    # but critically: Romania must not appear as oman
    oman_rows = [r for r in res.staging_rows if "oman" in r.indicator_slug_raw]
    for row in oman_rows:
        # If an oman row exists, it must come from a value > 10 USD million
        # (Romania->Nepal ~4.3 USD million in 2021; real Oman->Nepal is None)
        assert row.value > 10.0, (
            f"Suspicious low oman value {row.value} - likely Romania false positive"
        )
